<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="AAS" failures="2" tests="2" name="ValidationTitle" time="15.127" errors="0" timestamp="25 Sep 2021 05:52:42 GMT">
  <testcase classname="Academy.ValidationTitle" name="ValidateHeader" time="0.06">
    <failure type="java.lang.AssertionError" message="expected [An Academy to learn Everything about Testing] but found [AN ACADEMY TO LEARN EVERYTHING ABOUT TESTING]">
      <![CDATA[java.lang.AssertionError: expected [An Academy to learn Everything about Testing] but found [AN ACADEMY TO LEARN EVERYTHING ABOUT TESTING]
	at Academy.ValidationTitle.ValidateHeader(ValidationTitle.java:46)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- ValidateHeader -->
  <testcase classname="Academy.ValidationTitle" name="basePageNavigation" time="0.185">
    <failure type="java.lang.AssertionError" message="expected [FEATURED COURSES123] but found [FEATURED COURSES]">
      <![CDATA[java.lang.AssertionError: expected [FEATURED COURSES123] but found [FEATURED COURSES]
	at Academy.ValidationTitle.basePageNavigation(ValidationTitle.java:36)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
... Removed 21 stack frames]]>
    </failure>
  </testcase> <!-- basePageNavigation -->
</testsuite> <!-- ValidationTitle -->
